import { Sparkles } from 'lucide-react';

// Renders a table column header with an AI badge when the column was
// generated by the enrichment pipeline. Regular columns render plainly.
// Pass isAi=true for any column whose name appears in added_columns.
export function AiColumnHeader({ name, isAi }: { name: string; isAi: boolean }) {
  if (!isAi) return <>{name}</>;

  return (
    <span className="inline-flex items-center gap-1">
      {/* Gradient text — mimics the Gemini/AI colour language (blue → violet → pink) */}
      <span
        className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 bg-clip-text text-transparent font-semibold"
      >
        {name}
      </span>
      <Sparkles className="w-3 h-3 text-violet-400 flex-shrink-0" />
    </span>
  );
}
